[package]
name = "my_game"
version = "0.1.0"
edition = "2018"

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }

heron = { version = "0.11.0", features = ["3d"] }

[toolchain]
channel = "nightly"